# Generated by Django 4.2.27 on 2025-12-29 21:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('finishe', 'finished'), ('abandoned', 'abandoned')], default='active', max_length=16)),
                ('queue', models.JSONField(default=list)),
                ('index', models.PositiveIntegerField(default=0)),
                ('current_nonce', models.CharField(blank=True, default='', max_length=36)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='core.deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.PositiveSmallIntegerField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('due_before', models.DateTimeField(blank=True, null=True)),
                ('due_after', models.DateTimeField(blank=True, null=True)),
                ('ease_before', models.FloatField(blank=True, null=True)),
                ('ease_after', models.FloatField(blank=True, null=True)),
                ('interval_before', models.PositiveIntegerField(blank=True, null=True)),
                ('interval_after', models.PositiveIntegerField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='core.flashcard')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='core.deck')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='study.studysession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField(default=datetime.datetime(2025, 12, 29, 21, 18, 36, 257296, tzinfo=datetime.timezone.utc))),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('ease', models.FloatField(default=2.5)),
                ('interval_days', models.PositiveIntegerField(default=0)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('lapses', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(choices=[('new', 'new'), ('learning', 'learning'), ('review', 'review'), ('relearning', 'relearning')], default='new', max_length=16)),
                ('algorithm', models.CharField(default='sm2', max_length=16)),
                ('algo_state', models.JSONField(blank=True, default=dict)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='core.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'status', 'started_at'], name='study_study_user_id_638050_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['deck', 'status'], name='study_study_deck_id_653c71_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewlog',
            index=models.Index(fields=['user', 'reviewed_at'], name='study_revie_user_id_9971e9_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewlog',
            index=models.Index(fields=['user', 'deck', 'reviewed_at'], name='study_revie_user_id_002ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='cardprogress',
            index=models.Index(fields=['user', 'due_at'], name='study_cardp_user_id_7bbab2_idx'),
        ),
        migrations.AddIndex(
            model_name='cardprogress',
            index=models.Index(fields=['user', 'card'], name='study_cardp_user_id_d875a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='cardprogress',
            constraint=models.UniqueConstraint(fields=('user', 'card'), name='uniq_user_card_progress'),
        ),
    ]
