# Generated by Django 4.2.27 on 2025-12-29 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardprogress',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 29, 15, 56, 13, 639650, tzinfo=datetime.timezone.utc)),
        ),
    ]
