# Generated by Django 4.2.27 on 2025-12-29 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_generated', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('version', models.CharField(blank=True, max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['language__name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('translation', models.CharField(blank=True, max_length=400)),
                ('context_sentence', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('frequency_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.language')),
            ],
            options={
                'ordering': ['language__name', 'frequency_rank', 'word'],
            },
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_cards', to='core.flashcard')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_cards', to='core.deck')),
            ],
            options={
                'ordering': ['deck_id', 'position'],
            },
        ),
        migrations.AddField(
            model_name='deck',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='core.language'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['language', 'frequency_rank'], name='core_flashc_languag_20a1f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='flashcard',
            constraint=models.UniqueConstraint(fields=('language', 'word'), name='uniq_word_per_language'),
        ),
        migrations.AddIndex(
            model_name='deckcard',
            index=models.Index(fields=['deck', 'position'], name='core_deckca_deck_id_1d6846_idx'),
        ),
        migrations.AddIndex(
            model_name='deckcard',
            index=models.Index(fields=['deck', 'card'], name='core_deckca_deck_id_52f0a5_idx'),
        ),
        migrations.AddConstraint(
            model_name='deckcard',
            constraint=models.UniqueConstraint(fields=('deck', 'card'), name='uniq_card_in_deck'),
        ),
        migrations.AddIndex(
            model_name='deck',
            index=models.Index(fields=['language', 'is_generated'], name='core_deck_languag_2898f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='deck',
            constraint=models.UniqueConstraint(fields=('language', 'title'), name='uniq_deck_title_per_language'),
        ),
    ]
